# Generated by Django 4.0.3 on 2022-03-03 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_rename_user_profile_profile_profile_followers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile',
            new_name='user',
        ),
    ]
