# Generated by Django 4.0.3 on 2022-03-03 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_remove_profile_followers_remove_profile_following_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfollowing',
            old_name='follower',
            new_name='following_profile_id',
        ),
        migrations.RenameField(
            model_name='userfollowing',
            old_name='following',
            new_name='profile_id',
        ),
    ]
