# Generated by Django 4.0.3 on 2022-03-03 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_profile_follower_profile_followings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='follower',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='followings',
        ),
        migrations.RemoveField(
            model_name='userfollowing',
            name='follower',
        ),
        migrations.RemoveField(
            model_name='userfollowing',
            name='followings',
        ),
        migrations.AddField(
            model_name='userfollowing',
            name='followers',
            field=models.ManyToManyField(blank=True, to='user.userfollowing'),
        ),
        migrations.AddField(
            model_name='userfollowing',
            name='following',
            field=models.ManyToManyField(blank=True, to='user.userfollowing'),
        ),
    ]
