# Generated by Django 4.0.3 on 2022-03-03 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_remove_profile_follower_remove_profile_followings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfollowing',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='userfollowing',
            name='following',
        ),
    ]
