# Generated by Django 4.0.3 on 2022-03-03 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_remove_userfollowing_followers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfollowing',
            options={'ordering': ['-created']},
        ),
    ]
