# Generated by Django 4.0.3 on 2022-03-03 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_alter_userfollowing_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_post', to='user.profile'),
        ),
        migrations.AlterUniqueTogether(
            name='userfollowing',
            unique_together={('profile_id', 'following_profile_id')},
        ),
    ]
