# Generated by Django 4.0.3 on 2022-03-07 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_alter_post_posted_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=500, null=True)),
                ('text', models.CharField(blank=True, max_length=500, null=True)),
                ('OtherUser_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user98', to=settings.AUTH_USER_MODEL)),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user99', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
