# Generated by Django 4.0.3 on 2022-03-21 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_sharesettings_likesettings_commentsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotifications',
            name='OtherUser_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user98', to='user.profile'),
        ),
        migrations.AlterField(
            model_name='usernotifications',
            name='User_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user99', to='user.profile'),
        ),
    ]
