# Generated by Django 4.0.3 on 2022-03-21 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_alter_usernotifications_otheruser_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usernotifications',
            name='OtherUser_id',
        ),
        migrations.AddField(
            model_name='usernotifications',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.post'),
        ),
    ]
